### ISSUE TITLE
Support gear S3

### ISSUE THREAD

**Issue by kiokoman** [tesurijp/TOTP-Tizen#4]
i was able to make it work under my gear s3, with debug there was an error showing up, unable to find reference TITLE,
i modified source file index.html where there is <script src="language.js"></script> in <script src="language/en/language.js"></script>
rebuild and installed on my gear s3 with tizen studio, now it works for me
hope it help

**Comment by tesurijp** [comment]
Gear S3 is supported.
This is a locale problem. Fix to work on locale other than En / JP.
