### ISSUE TITLE
Amazonでは使用出来ません。

### ISSUE THREAD

**Issue by mvevitsis** [tesurijp/TOTP-Tizen#7]
ちゃんとtxtファイルに入れても0000しか表示されません。

**Comment by dimon222** [comment]
It behaves like that for tokens that have padding, mentioned in #6 and #3

Fix is proposed in #5 but sadly this repo doesn't seem maintained so nobody can merge

**Comment by slopsommelier** [comment]
Has anyone been able to build a TPK with it fixed? I couldn't get it to build.

**Comment by slopsommelier** [comment]
I merged the fix in #5 with the implementation in #6 and built, pushed to device still doesn't work.

**Comment by tesurijp** [comment]
アマゾンの 2段階認証で提供されるキーは、桁数に誤りがあるため、正常にデコードできませんでした。アマゾン用の補正処理を加えた版を作成しました。
Galaxy Appsで現在、審査中なので、しばらくすれば公開されるはずです。

Amazon JP 's key is not correct. It can't decode as base32.
I add temporary support for AmazonJP
I already uploaded it to Galaxy Apps. It will be open after check by sumsung store.
